
package s10_proyectofinal_mia.belen;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane; 

public class MenuMain extends javax.swing.JFrame {

    static Random ran = new Random(); 
    static Scanner papoy = new Scanner(System.in); 
    
    ChatsDeCuisine cdc = new ChatsDeCuisine(); 
    Login Log = new Login(); 
    MundoPatitos MP = new MundoPatitos(); 
        
    public MenuMain() {
        this.setLocation(500, 170);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Chats = new javax.swing.JButton();
        EleganciaBotan = new javax.swing.JButton();
        MundoPatos = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("--- MENU ---");

        Chats.setBackground(new java.awt.Color(0, 51, 51));
        Chats.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Chats.setText("Les Chats de Cuisine");
        Chats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChatsMouseClicked(evt);
            }
        });

        EleganciaBotan.setBackground(new java.awt.Color(0, 51, 51));
        EleganciaBotan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        EleganciaBotan.setText("Elegancia Botanica");
        EleganciaBotan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EleganciaBotanMouseClicked(evt);
            }
        });

        MundoPatos.setBackground(new java.awt.Color(0, 51, 51));
        MundoPatos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        MundoPatos.setText("MundoPato");
        MundoPatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MundoPatosMouseClicked(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(0, 51, 51));
        BotonSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Chats, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(EleganciaBotan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MundoPatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Chats, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EleganciaBotan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(MundoPatos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChatsMouseClicked
        this.setVisible(false);
        System.out.println("Bienvenido a Les Chats de Cuisine!\nLas Reglas son las siguientes: \n"
                        + "1. Debes tirar el dado para determinar tu avance\n2. Cuando encuentres una papa la guardaras en tu canasta\n"
                        + "3. Al encontrar una cacerola podras revisar tu canasta para determinar si puedes cocinar tus papas (tambien decidiras si cocinar o no)\n"
                        + "4. Siempre responde con S o N, cualquier otra respuesta sera considerada como un Salir"
                        + " \n¿Deseas ver tu tablero inicial para comenzar? - Responder S o N\n"); 
                char resp_user = papoy.next().charAt(0); 
                if(resp_user == 'S' || resp_user == 's'){//Ingreso inicial
                    
                    int tablero_elec = ran.nextInt(1,4); 
                    char [][] tablero = cdc.escoger_matriz(tablero_elec); 
                    System.out.println("----- Tablero Inicial -----");
                    cdc.tabInicial(tablero);
                    System.out.println("Este es tu tablero\n¿Comenzamos?\nS o N");
                    char comenzar = papoy.next().charAt(0); 
                    if (comenzar == 'S' || comenzar == 's'){
                        cdc.Jugar(tablero);
                        System.out.println(" ");
                    }
                
                }else if (resp_user == 'N' || resp_user == 'n'){
                    System.out.println("No jugaremos");
                
                }else{
                    System.out.println("Caracter no valido, lo cual invalida el juego");
                }
                System.out.println("¿Desea volver al Menu Principal?");
            char menu = papoy.next().charAt(0); 
            if (menu == 's' || menu == 'S'){
               this.setVisible(true);
            }else{
                System.exit(0);
            }
        
        
        
    }//GEN-LAST:event_ChatsMouseClicked

    private void EleganciaBotanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EleganciaBotanMouseClicked
        
        Log.setVisible(true);
        this.setVisible(false);
//        String op = JOptionPane.showInputDialog(null, "¿Desea volver al Menu Principal?\nS o N"); 
//        char resp = op.charAt(0); 
//        if (resp == 'S' || resp == 's'){
//            this.setVisible(true);
//        }else if(resp == 'N' || resp == 'n'){
//            System.exit(0);
//        }else{
//            JOptionPane.showMessageDialog(null, "Caracter Invalido\nSaliendo del sistema");
//        }
         
         
           
    }//GEN-LAST:event_EleganciaBotanMouseClicked

    private void MundoPatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MundoPatosMouseClicked
        this.setVisible(false);
        MP.setLocation(250, 30);
        MP.setVisible(true); 
        
        
        
    }//GEN-LAST:event_MundoPatosMouseClicked

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        System.exit(0); 
        
    }//GEN-LAST:event_BotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton Chats;
    private javax.swing.JButton EleganciaBotan;
    private javax.swing.JButton MundoPatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
